//! DNS-over-HTTPS (DoH) connection monitor.
//!
//! Tracks which applications are connecting to known DoH endpoints and flags
//! suspicious usage. Non-browser applications using DoH are likely malware
//! performing C2 over encrypted DNS. Browsers using DoH bypass the system DNS
//! sinkhole, undermining domain-level protections.

use std::collections::HashSet;

use serde::{Deserialize, Serialize};

use crate::dns_sinkhole::DnsSinkhole;

/// Severity level for a DoH connection alert.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum DohAlertSeverity {
    /// Informational: browser using DoH when system DNS should be used.
    Info,
    /// Warning: browser using DoH, bypassing sinkhole protections.
    Warning,
    /// Critical: non-browser process using DoH (likely malware C2).
    Critical,
}

/// An alert generated by the DoH monitor.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct DohAlert {
    /// Name of the process that triggered the alert.
    pub process_name: String,
    /// Binary path of the process, if known.
    pub binary_path: Option<String>,
    /// Severity of the alert.
    pub severity: DohAlertSeverity,
    /// Human-readable reason for the alert.
    pub reason: String,
    /// The DoH provider being contacted.
    pub provider: String,
    /// Destination IP address, if known.
    pub dest_ip: Option<String>,
    /// Destination port.
    pub dest_port: Option<u16>,
}

/// An observed outbound connection for DoH analysis.
#[derive(Debug, Clone)]
pub struct ObservedConnection {
    /// Process name.
    pub process_name: String,
    /// Binary path of the process, if known.
    pub binary_path: Option<String>,
    /// Destination IP address as a string.
    pub dest_ip: Option<String>,
    /// Destination port.
    pub dest_port: Option<u16>,
    /// Destination domain (from SNI or Host header).
    pub domain: Option<String>,
}

/// Monitors outbound connections for DNS-over-HTTPS bypass attempts.
///
/// Distinguishes between browser and non-browser processes: non-browser
/// applications using DoH are flagged as critical (likely malware C2),
/// while browsers using DoH are flagged as warnings (bypassing system DNS).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DohMonitor {
    /// Set of process names considered to be browsers.
    known_browsers: HashSet<String>,
    /// Whether to flag browser DoH usage (bypass of system DNS).
    flag_browser_doh: bool,
}

impl Default for DohMonitor {
    fn default() -> Self {
        Self::new()
    }
}

impl DohMonitor {
    /// Create a new DoH monitor with default browser list.
    pub fn new() -> Self {
        let mut known_browsers = HashSet::new();
        for name in Self::default_browsers() {
            known_browsers.insert(name.to_string());
        }
        Self {
            known_browsers,
            flag_browser_doh: true,
        }
    }

    /// Set whether to flag browser DoH usage.
    ///
    /// When enabled, browsers connecting to DoH endpoints are flagged as
    /// warnings because they bypass the system DNS sinkhole.
    pub fn set_flag_browser_doh(&mut self, flag: bool) {
        self.flag_browser_doh = flag;
    }

    /// Add a process name to the known browsers list.
    pub fn add_known_browser(&mut self, name: &str) {
        self.known_browsers.insert(name.to_lowercase());
    }

    /// Remove a process name from the known browsers list.
    pub fn remove_known_browser(&mut self, name: &str) -> bool {
        self.known_browsers.remove(&name.to_lowercase())
    }

    /// Check whether a process name is a known browser.
    pub fn is_browser(&self, process_name: &str) -> bool {
        self.known_browsers.contains(&process_name.to_lowercase())
    }

    /// Analyze a set of observed connections and return DoH alerts.
    ///
    /// Each connection is checked against known DoH endpoints. Non-browser
    /// processes get `Critical` alerts; browsers get `Warning` alerts (if
    /// `flag_browser_doh` is enabled).
    pub fn analyze_connections(&self, connections: &[ObservedConnection]) -> Vec<DohAlert> {
        let mut alerts = Vec::new();

        for conn in connections {
            let is_doh = DnsSinkhole::is_doh_endpoint(
                conn.dest_ip.as_deref(),
                conn.dest_port,
                conn.domain.as_deref(),
            );

            if !is_doh {
                continue;
            }

            let provider = DnsSinkhole::identify_doh_provider(
                conn.dest_ip.as_deref(),
                conn.dest_port,
                conn.domain.as_deref(),
            )
            .unwrap_or("Unknown")
            .to_string();

            let is_browser = self.is_browser(&conn.process_name);

            if is_browser {
                if self.flag_browser_doh {
                    alerts.push(DohAlert {
                        process_name: conn.process_name.clone(),
                        binary_path: conn.binary_path.clone(),
                        severity: DohAlertSeverity::Warning,
                        reason: format!(
                            "Browser '{}' is using DoH ({}), bypassing system DNS sinkhole",
                            conn.process_name, provider
                        ),
                        provider,
                        dest_ip: conn.dest_ip.clone(),
                        dest_port: conn.dest_port,
                    });
                }
            } else {
                alerts.push(DohAlert {
                    process_name: conn.process_name.clone(),
                    binary_path: conn.binary_path.clone(),
                    severity: DohAlertSeverity::Critical,
                    reason: format!(
                        "Non-browser process '{}' is using DoH ({}) — possible malware C2 channel",
                        conn.process_name, provider
                    ),
                    provider,
                    dest_ip: conn.dest_ip.clone(),
                    dest_port: conn.dest_port,
                });
            }
        }

        alerts
    }

    /// Default list of known browser process names.
    fn default_browsers() -> Vec<&'static str> {
        vec![
            "firefox",
            "firefox-esr",
            "chromium",
            "chromium-browser",
            "chrome",
            "google-chrome",
            "google-chrome-stable",
            "brave",
            "brave-browser",
            "vivaldi",
            "vivaldi-bin",
            "opera",
            "epiphany",
            "epiphany-browser",
            "midori",
            "tor-browser",
            "librewolf",
            "waterfox",
            "ungoogled-chromium",
            "falkon",
            "konqueror",
            "surf",
            "qutebrowser",
            "nyxt",
            "min",
            "edge",
            "msedge",
            "microsoft-edge",
        ]
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_conn(
        process: &str,
        ip: Option<&str>,
        port: Option<u16>,
        domain: Option<&str>,
    ) -> ObservedConnection {
        ObservedConnection {
            process_name: process.to_string(),
            binary_path: None,
            dest_ip: ip.map(String::from),
            dest_port: port,
            domain: domain.map(String::from),
        }
    }

    #[test]
    fn test_non_browser_doh_flagged_critical() {
        let monitor = DohMonitor::new();
        let connections = vec![
            make_conn("malware_agent", Some("1.1.1.1"), Some(443), None),
        ];
        let alerts = monitor.analyze_connections(&connections);
        assert_eq!(alerts.len(), 1);
        assert_eq!(alerts[0].severity, DohAlertSeverity::Critical);
        assert_eq!(alerts[0].process_name, "malware_agent");
        assert_eq!(alerts[0].provider, "Cloudflare");
    }

    #[test]
    fn test_browser_doh_flagged_warning() {
        let monitor = DohMonitor::new();
        let connections = vec![
            make_conn("firefox", Some("8.8.8.8"), Some(443), None),
        ];
        let alerts = monitor.analyze_connections(&connections);
        assert_eq!(alerts.len(), 1);
        assert_eq!(alerts[0].severity, DohAlertSeverity::Warning);
        assert_eq!(alerts[0].process_name, "firefox");
        assert_eq!(alerts[0].provider, "Google");
    }

    #[test]
    fn test_browser_doh_not_flagged_when_disabled() {
        let mut monitor = DohMonitor::new();
        monitor.set_flag_browser_doh(false);
        let connections = vec![
            make_conn("firefox", Some("8.8.8.8"), Some(443), None),
        ];
        let alerts = monitor.analyze_connections(&connections);
        assert!(alerts.is_empty());
    }

    #[test]
    fn test_non_doh_traffic_not_flagged() {
        let monitor = DohMonitor::new();
        let connections = vec![
            make_conn("curl", Some("93.184.216.34"), Some(443), None),
            make_conn("apt", Some("151.101.2.132"), Some(443), None),
        ];
        let alerts = monitor.analyze_connections(&connections);
        assert!(alerts.is_empty());
    }

    #[test]
    fn test_multiple_doh_connections_mixed() {
        let monitor = DohMonitor::new();
        let connections = vec![
            make_conn("firefox", Some("1.1.1.1"), Some(443), None),
            make_conn("suspicious_bin", Some("8.8.8.8"), Some(443), None),
            make_conn("curl", Some("93.184.216.34"), Some(443), None),
            make_conn("chrome", None, Some(443), Some("dns.google")),
        ];
        let alerts = monitor.analyze_connections(&connections);
        assert_eq!(alerts.len(), 3);

        // firefox -> Warning
        assert_eq!(alerts[0].severity, DohAlertSeverity::Warning);
        assert_eq!(alerts[0].process_name, "firefox");

        // suspicious_bin -> Critical
        assert_eq!(alerts[1].severity, DohAlertSeverity::Critical);
        assert_eq!(alerts[1].process_name, "suspicious_bin");

        // chrome -> Warning
        assert_eq!(alerts[2].severity, DohAlertSeverity::Warning);
        assert_eq!(alerts[2].process_name, "chrome");
    }

    #[test]
    fn test_is_browser_detection() {
        let monitor = DohMonitor::new();
        assert!(monitor.is_browser("firefox"));
        assert!(monitor.is_browser("Firefox")); // case-insensitive
        assert!(monitor.is_browser("chrome"));
        assert!(monitor.is_browser("brave"));
        assert!(monitor.is_browser("tor-browser"));
        assert!(!monitor.is_browser("curl"));
        assert!(!monitor.is_browser("malware_agent"));
        assert!(!monitor.is_browser("python3"));
    }

    #[test]
    fn test_add_custom_browser() {
        let mut monitor = DohMonitor::new();
        assert!(!monitor.is_browser("my-custom-browser"));

        monitor.add_known_browser("my-custom-browser");
        assert!(monitor.is_browser("my-custom-browser"));
    }

    #[test]
    fn test_remove_browser() {
        let mut monitor = DohMonitor::new();
        assert!(monitor.is_browser("firefox"));

        assert!(monitor.remove_known_browser("firefox"));
        assert!(!monitor.is_browser("firefox"));
    }

    #[test]
    fn test_alert_severity_ordering() {
        // Critical should be greater than Warning, which is greater than Info.
        assert!(DohAlertSeverity::Critical > DohAlertSeverity::Warning);
        assert!(DohAlertSeverity::Warning > DohAlertSeverity::Info);
    }

    #[test]
    fn test_doh_via_domain_non_browser() {
        let monitor = DohMonitor::new();
        let connections = vec![
            make_conn("python3", None, Some(443), Some("cloudflare-dns.com")),
        ];
        let alerts = monitor.analyze_connections(&connections);
        assert_eq!(alerts.len(), 1);
        assert_eq!(alerts[0].severity, DohAlertSeverity::Critical);
        assert_eq!(alerts[0].provider, "Cloudflare");
    }

    #[test]
    fn test_doh_alert_has_connection_details() {
        let monitor = DohMonitor::new();
        let connections = vec![ObservedConnection {
            process_name: "sketchy".to_string(),
            binary_path: Some("/tmp/sketchy".to_string()),
            dest_ip: Some("9.9.9.9".to_string()),
            dest_port: Some(443),
            domain: None,
        }];
        let alerts = monitor.analyze_connections(&connections);
        assert_eq!(alerts.len(), 1);
        assert_eq!(alerts[0].dest_ip.as_deref(), Some("9.9.9.9"));
        assert_eq!(alerts[0].dest_port, Some(443));
        assert_eq!(alerts[0].binary_path.as_deref(), Some("/tmp/sketchy"));
        assert_eq!(alerts[0].provider, "Quad9");
    }
}
